version: "3.9"
services:
  memcached:
    image: "memcached:alpine3.14"
    container_name: "memcached"
    ports:
      - "11211:11211"
    expose:
      - 11211
    networks:
      - db_network
  movies_service:
    build: .
    container_name: "movies"
    ports:
      - "8000:8000"
    depends_on:
      - memcached
    networks:
      - db_network

networks:
  db_network: {}